# Generated by Django 3.2.9 on 2022-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceLengthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='result_file',
            field=models.CharField(default='', max_length=256),
        ),
    ]
