# Generated by Django 3.2.9 on 2022-01-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0002_auto_20220117_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SequenceLengthAnalysis',
        ),
    ]
