# Generated by Django 3.2.9 on 2022-01-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220117_1235'),
        ('clustering', '0003_delete_sequencelengthanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_length', models.PositiveIntegerField()),
                ('clustering_type', models.CharField(max_length=50)),
                ('num_clusters', models.PositiveIntegerField()),
                ('results', models.JSONField()),
                ('analysis_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.analysisfile')),
            ],
        ),
    ]
