# Generated by Django 3.2.9 on 2022-01-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220117_1235'),
        ('clustering', '0005_alter_clusteringanalysis_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_length', models.PositiveIntegerField()),
                ('scores', models.JSONField(null=True)),
                ('analysis_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.analysisfile')),
            ],
        ),
    ]
