# Generated by Django 3.2.9 on 2022-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0008_delete_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringanalysis',
            name='sequences',
            field=models.JSONField(null=True),
        ),
    ]
