# Generated by Django 3.2.9 on 2022-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancesanalysis',
            name='distances',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='distancesbetweenresultsanalysis',
            name='distances',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sequencelengthanalysis',
            name='sequence_lengths',
            field=models.JSONField(null=True),
        ),
    ]
